language: generic
sudo: false

# keep this blank to make sure there are no before_install steps
before_install:

install:
  - ./install.sh
script:
  - vim '+qa' && vim '+PlugInstall --sync' '+qa'
os:
  - linux
  - osx
notifications:
  email: false
